### ISSUE TITLE
Executing plugin

### ISSUE THREAD

**Issue by GTP95** [engeljh/vim-latexfmt#2]
Greetings,

Sorry for the trivial question, but how do I execute this plugin after installing it? The README says "Before creating this gif, I mapped 'K' to \<Plug\>latexfmt_format", so I tried executing both `<Plug>latexfmt_format` and `latexfmt_format` in command mode, to no avail. I don't have much experience with vim, so I would be glad if you could help me.
Regards,

GTP

**Comment by engeljh** [comment]
Hello,

In my .vimrc file I have

map <unique> <silent> <buffer> K <Plug>latexfmt_format

You don't need the options <unique>, <silent>, and <buffer>, and you can use some other sequence than K as the trigger.  You can also do the mapping from the  command line in the file you're editing  instead of in your .vimrc file (I think), or in any file that is sourced when vim is opened.

The file latexfmt.txt in the doc folder contains some of this info.

**Comment by engeljh** [comment]
Hi,

You can put

map K <Plug>latexfmt_format 

in your .vimrc.  Or you can map some other sequence than K.   Or you can put the mapping in some other file that gets sourced when vim is run.  Some of this info is in the doc file.
________________________________
From: Giacomo Tommaso Petrucci ***@***.***>
Sent: Tuesday, February 13, 2024 3:54 PM
To: engeljh/vim-latexfmt ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [engeljh/vim-latexfmt] Executing plugin (Issue #2)


Greetings,

Sorry for the trivial question, but how do I execute this plugin after installing it? The README says "Before creating this gif, I mapped 'K' to latexfmt_format", so I tried executing both <Plug>latexfmt_format and latexfmt_format in command mode, to no avail. I don't have much experience with vim, so I would be glad if you could help me.
Regards,

GTP

**Comment by GTP95** [comment]
It worked, thank you!
But I'm wondering: if I didn't want to map it to a key, would have been there a way to invoke it from command mode or in some other way? Sorry for the trivial question, I started customizing VIM with plugins only recently.

**Comment by engeljh** [comment]
If you look in the file tex.vim in the ftplugin directory, you'll see that <Plug>latexfmt_format is itself a mapping to a function call.  If you type, e.g.,

call latexfmt#FormatLines("n")

on the command line and hit return, it should work.  But it's not meant to be used that way.

________________________________
